# Generated by Django 5.2.3 on 2025-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('carbon_footprint', models.FloatField(help_text='in grams of CO₂ per item')),
                ('packaging_type', models.CharField(max_length=100)),
                ('eco_rating', models.IntegerField(help_text='1 to 5 stars')),
            ],
        ),
    ]
